Sous Chefs Adoption
sous-chefs/trusted_certificate pull request #35
Opened 2021-03-15 17:52 UTC by TheREK3R

# Description

Formally adopt this cookbook into Sous Chefs

## Issues Resolved

Adds new inspec tests

## Check List

- [X] All tests pass. See TESTING.md for details.
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable.

2021-03-15 19:13 UTC, ramereth requested changes

2021-03-15 19:13 UTC, ramereth commented on .github/workflows/ci.yml
> +          - 'amazonlinux'
Let's not worry about this platform, only test `amazonlinux-2`

2021-03-15 19:13 UTC, ramereth commented on metadata.rb
>  description 'Manages adding certificates to the OS trust store'
You forgot to fix the text above here.

2021-03-18 23:06 UTC, ramereth approved these changes

2021-03-18 23:06 UTC, merged

2021-03-18 23:06 UTC, kitchen-porter commented
Released as: [3.4.0](https://github.com/sous-chefs/trusted_certificate/releases/tag/3.4.0)